// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway.proto

/*
Package gateway is a generated protocol buffer package.

It is generated from these files:
	gateway.proto

It has these top-level messages:
	StreamInfo
	ReplyInfo
*/
package gateway

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StreamInfo struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *StreamInfo) Reset()                    { *m = StreamInfo{} }
func (m *StreamInfo) String() string            { return proto.CompactTextString(m) }
func (*StreamInfo) ProtoMessage()               {}
func (*StreamInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *StreamInfo) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type ReplyInfo struct {
	ErrCode uint64 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
}

func (m *ReplyInfo) Reset()                    { *m = ReplyInfo{} }
func (m *ReplyInfo) String() string            { return proto.CompactTextString(m) }
func (*ReplyInfo) ProtoMessage()               {}
func (*ReplyInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReplyInfo) GetErrCode() uint64 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *ReplyInfo) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*StreamInfo)(nil), "gateway.StreamInfo")
	proto.RegisterType((*ReplyInfo)(nil), "gateway.ReplyInfo")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RtcInterface service

type RtcInterfaceClient interface {
	CloseStream(ctx context.Context, in *StreamInfo, opts ...grpc.CallOption) (*ReplyInfo, error)
}

type rtcInterfaceClient struct {
	cc *grpc.ClientConn
}

func NewRtcInterfaceClient(cc *grpc.ClientConn) RtcInterfaceClient {
	return &rtcInterfaceClient{cc}
}

func (c *rtcInterfaceClient) CloseStream(ctx context.Context, in *StreamInfo, opts ...grpc.CallOption) (*ReplyInfo, error) {
	out := new(ReplyInfo)
	err := grpc.Invoke(ctx, "/gateway.RtcInterface/CloseStream", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RtcInterface service

type RtcInterfaceServer interface {
	CloseStream(context.Context, *StreamInfo) (*ReplyInfo, error)
}

func RegisterRtcInterfaceServer(s *grpc.Server, srv RtcInterfaceServer) {
	s.RegisterService(&_RtcInterface_serviceDesc, srv)
}

func _RtcInterface_CloseStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtcInterfaceServer).CloseStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway.RtcInterface/CloseStream",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtcInterfaceServer).CloseStream(ctx, req.(*StreamInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _RtcInterface_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.RtcInterface",
	HandlerType: (*RtcInterfaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CloseStream",
			Handler:    _RtcInterface_CloseStream_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway.proto",
}

func init() { proto.RegisterFile("gateway.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4f, 0x2c, 0x49,
	0x2d, 0x4f, 0xac, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xe4, 0xb8,
	0xb8, 0x82, 0x4b, 0x8a, 0x52, 0x13, 0x73, 0x3d, 0xf3, 0xd2, 0xf2, 0x85, 0x04, 0xb8, 0x98, 0xb3,
	0x53, 0x2b, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0x25, 0x5b, 0x2e, 0xce, 0xa0,
	0xd4, 0x82, 0x9c, 0x4a, 0xb0, 0xb4, 0x04, 0x17, 0x7b, 0x6a, 0x51, 0x91, 0x73, 0x7e, 0x4a, 0x2a,
	0x58, 0x09, 0x4b, 0x10, 0x8c, 0x2b, 0x24, 0xc6, 0xc5, 0x96, 0x5a, 0x54, 0xe4, 0x5b, 0x9c, 0x2e,
	0xc1, 0x04, 0xd6, 0x0b, 0xe5, 0x19, 0xb9, 0x71, 0xf1, 0x04, 0x95, 0x24, 0x7b, 0xe6, 0x95, 0xa4,
	0x16, 0xa5, 0x25, 0x26, 0xa7, 0x0a, 0x99, 0x71, 0x71, 0x3b, 0xe7, 0xe4, 0x17, 0xa7, 0x42, 0xec,
	0x14, 0x12, 0xd6, 0x83, 0x39, 0x0b, 0xe1, 0x08, 0x29, 0x21, 0xb8, 0x20, 0xdc, 0xe6, 0x24, 0x36,
	0xb0, 0xb3, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x17, 0xc2, 0x67, 0xc7, 0x00, 0x00,
	0x00,
}
